### ISSUE TITLE
`time` crate is broken for rust 1.80.0 at version 0.3.30

### ISSUE THREAD

**Issue by shadogar** [brycx/pasetors#129]
https://github.com/time-rs/time/issues/693

The fix is to update the crate version.

**Comment by shadogar** [comment]
Currently consumers of this crate using rust 1.80.0 are unable to compile due to this issue

**Comment by brycx** [comment]
Hi @shadogar,

Thanks for bringing a potential issue to my attention.

I just built and ran the tests in release mode locally for `1.80.0` and re-ran the daily tests in CI, that also run latest Rust on `stable` and `nightly` channels. Both compiled fine.

The `Cargo.toml` doesn't specify the SemVer patch version, so `time` should automatically be the newest & compatible version available at compile-time. This is what my build logs show both locally and in CI.

Try a `cargo update`, which should solve this. Or perhaps you meant for this to be more of a PSA-like issue?

**Comment by shadogar** [comment]
> Hi @shadogar,
> 
> Thanks for bringing a potential issue to my attention.
> 
> I just built and ran the tests in release mode locally for `1.80.0` and re-ran the daily tests in CI, that also run latest Rust on `stable` and `nightly` channels. Both compiled fine.
> 
> The `Cargo.toml` doesn't specify the SemVer patch version, so `time` should automatically be the newest & compatible version available at compile-time. This is what my build logs show both locally and in CI.
> 
> Try a `cargo update`, which should solve this. Or perhaps you meant for this to be more of a PSA-like issue (otherwise, I'll close this issue for now as this problem is not fixable in `pasetors`)?

Indeed running `cargo update` did fix the issue. Thank you! I'll close the issue.

**Comment by liudonghua123** [comment]
I have the similar issues when build a tauri app on macos. It's strange that the tauri app build successfully on linux and macos, but not on macos.

I also noticed that it seems [`Compiling tao`](https://github.com/tauri-apps/tao) logging appears on macos building logs, but not on linux.

See https://github.com/liudonghua123/pxt-microbit-app/actions/runs/10517054766/job/29140512953.
