### ISSUE TITLE
Bind Keys to Version and Purpose

### ISSUE THREAD

**Issue by paragonie-security** [brycx/pasetors#14]
https://github.com/brycx/pasetors/blob/fa3360d32ba089cc9a74cd9225266a8df92e7543/src/version2.rs#L162

See https://github.com/paseto-standard/paseto-spec/blob/master/docs/02-Implementation-Guide/03-Algorithm-Lucidity.md

Right now, byte arrays are accepted by this API. There's no mechanism to prevent a user from using a v2 public key as a v2 local key.

**Comment by brycx** [comment]
Thanks for the suggestion @paragonie-security. This sounds like a good idea.


I'll include this in the next release.
