### ISSUE TITLE
Implement (De)Serialize for more types

### ISSUE THREAD

**Issue by tomtom5152** [brycx/pasetors#150]
As these tokens are often passed around a lot, it would be really helpful if more types implemented `(De)Serialize`, especially `(Un)TrustedToken` and `Claims` as it would be great to pass these over an API.

I've got `Claims` working using `(de)serialize_with`  and `to_string()`/`from_string()` but it would be an even better DX if this was handled transparently internally.

Happy to submit a PR if you are happy with this approach or open to suggestions for alternatives.

**Comment by brycx** [comment]
Hi @tomtom5152,

I definitely see benefits in providing `Serialize`/`Deserialize` impls for types that are passed around a lot, and can't come up with any concerns for the types you've mentioned so far.

I'd be happy to review a PR if you have the time to submit one. Perhaps we can start with the `UntrustedToken`, `TrustedToken` and `Claims` types. Based on that, we can see if any of it needs changing or other types should have it as well?
