### ISSUE TITLE
Why `TryFrom<String>` not `TryFrom<&str>`?

### ISSUE THREAD

**Issue by Eh2406** [brycx/pasetors#53]
Why `TryFrom<String>` not `TryFrom<&str>`?
For example here https://docs.rs/pasetors/0.5.0-alpha.5/src/pasetors/paserk.rs.html#129-141
Why do we need to own the string in order to convert it into a `pasetors` type?

**Comment by brycx** [comment]
There should be no reason and this should definitely be `TryFrom<&str>`. I don't know why this wasn't so to begin with.

**Comment by brycx** [comment]
Included in the latest prerelease: https://crates.io/crates/pasetors/0.5.0-alpha.6
