### ISSUE TITLE
`AsymmetricPublicKey` does not implement clone?

### ISSUE THREAD

**Issue by Eh2406** [brycx/pasetors#54]
I was surprised to discover that `AsymmetricPublicKey` does not implement clone. I was wondering if there's a reason?
If not we should audit all types for clone impls.

**Comment by brycx** [comment]
I'm not at a computer atm, but I can't think of a reason. But if it's missing there, then yes we should check the remaining types as well.

**Comment by brycx** [comment]
Included in the latest prerelease: https://crates.io/crates/pasetors/0.5.0-alpha.6
